name: DreamBlockParty
main: net.perfectdreams.dreamblockparty.DreamBlockParty
version: 1.0-SNAPSHOT
author: MrPowerGamerBR
api-version: 1.13
depend: ["DreamCore", "DreamCash", "DreamChat", "DreamMapWatermarker", "DreamCorreios"]
