package net.perfectdreams.dreamsinuca.sinuca

enum class FinishReason {
    POOL_TABLE_TEAR_DOWN,
    PLAYER_TOO_FAR_AWAY,
    PLAYER_QUIT,
    PLAYER_TOOK_TOO_LONG,
    EIGHT_BALL_POCKETED_DURING_BREAK,
    POCKETED_EIGHT_BALL_BEFORE_POCKETING_OWN_BALLS,
    POCKETED_EIGHT_BALL_AND_CUEBALL_AT_THE_SAME_TIME,
    POCKETED_ALL_BALLS
}