# This is a basic workflow to help you get started with Actions

name: Build SparklyPower Plugins

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, 1.19.2-stuff, ver/1.20, ver/1.20.6, ver/1.21, ver/1.20.6-directors-cut, ver/1.21.1, ver/1.21.3 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 21

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: build

    # Upload Artifacts to GitHub
    - uses: actions/upload-artifact@v4
      name: "Upload Common Plugins"
      with:
        name: SparklyPower Common Plugins
        path: "common/*/build/libs/*.jar"

    - uses: actions/upload-artifact@v4
      name: "Upload Bukkit Plugins"
      with:
        name: SparklyPower Bukkit Plugins - Mojang Mappings
        path: "bukkit/*/build/libs/*.jar"

    - uses: actions/upload-artifact@v4
      name: "Upload Velocity Plugins"
      with:
        name: SparklyPower Velocity Plugins
        path: "velocity/*/build/libs/*.jar"
